version: '3'
services:
  vue-app:
    image: damehal/devenv-vuecli
    ports:  # ローカルホストURL: http://localhost:8081/
      - "8080:8080"
    volumes:  # 共有するディレクトリをマウント
      - ./app:/home/nodeuser/sharing-lunch
    container_name: sharing-lunch
    command: /bin/bash -c "cd sharing-lunch && npm run dev"
