version: 2
jobs:
  build:
    docker: # Dockerイメージの指定
      - image: damehal/devenv-vuecli
    working_directory: /home/nodeuser/sharing-lunch # カレントディレクトリの指定
    environment:
      - SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    steps:
      - checkout
      - run: # ビルド開始通知
          name: Notification to Slack "Build Started"
          command: |
            curl -X POST $SLACK_WEBHOOK_URL \
            -H 'content-type: application/json' \
            -d '{
              "text": "Build Started!"
            }'
      - run: #test
          name: checkout
          command: |
            pwd \
            ls -la
      - run:
          name: Unit Test
          command: |
            npm install \
            npm run unit --silent
