version: 2
jobs:
  build:
    docker: # 利用するDockerイメージの指定
      - image: damehal/devenv-vuecli
    working_directory: /home/nodeuser/sharing-lunch # カレントディレクトリの指定
    environment:
      - SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    steps:
      - run: # ビルド開始通知
          name: Notification to Slack "Started Build"
          command: |
            curl -X POST $SLACK_WEBHOOK_URL \
            -H 'content-type: application/json' \
            -d '{
              "text": "Started Buld!"
            }'
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: Unit Test
          command: npm run unit
