version: 2
jobs:
  build:
    docker: # Dockerイメージの指定
      - image: damehal/devenv-vuecli

    working_directory: sharing-lunch # カレントディレクトリの指定

    steps:
      - checkout
      - run:
          name: Test echo
          command: echo 'hello CircleCI'
      - run:
          name: Test pwd
          command: pwd
      - run:
          name: Test ls
          command: ls -la
      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
#
#      - run: yarn install
#
#      - save_cache:
#          paths:
#            - node_modules
#          key: v1-dependencies-{{ checksum "package.json" }}
#
#      # run tests!
#      - run: yarn test
